# Generated by Django 3.0.3 on 2020-03-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('brief', models.TextField()),
                ('content', models.TextField()),
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='app_projects/images/')),
            ],
        ),
    ]
